def test_truthy(value, boolean)
  puts "#{caller_locations[0].lineno}: #{value} is #{boolean}"
end

test_truthy((true && true), true)
test_truthy((false && true), false)
test_truthy((1 == 1 && 2 == 1), false)
test_truthy(('test' == 'test'), true)
test_truthy((1 ==1 || 2!= 1), true)
test_truthy((true && 1 == 1), true)
test_truthy((false && 0 != 0), false)
test_truthy((false && 0 != 0), false)
test_truthy((true || 1 == 1), true)
test_truthy(('test' == 'testing'), false)
test_truthy((1 != 0 && 2 == 1), false)
test_truthy(('test' != 'testing'), false)
test_truthy(('test' == 1), false)
test_truthy((!(true && false)), true)
test_truthy((!(1 == 1 && 0 !=1)), false)
test_truthy((!(10 == 1 || 1000 == 1000)), false)
test_truthy((!(1 != 10 || 3 == 4)), false)
test_truthy((!('testing' == 'testing' && 'Zed' == 'Cool Guy')), true)
test_truthy((1 == 1 && (!('testing' == 1 || 1 == 0))), true)
test_truthy(('chunky' == 'bacon' && (!(3 == 4 || 3 == 3))), false)
test_truthy((3 == 3 && (!('testing' == 'testing' || 'Ruby' == 'Fun'))), false)
